"""Pinned legacy Greek entities used by the audited BibIt TEI snapshot.

The allowlist contains only names observed in the 2026-08-09 canonical TEI
download. Values were resolved from BibIt's public numeric-entity DTD whose
SHA-256 is 2073624517861fd673fba09b8153e0d481e058cb091dd17e59262bb04b9c1aa5.
The XML parser never loads that external DTD.
"""

from __future__ import annotations


BIBIT_LEGACY_ENTITIES = {
    "Agr": "Α",
    "Bgr": "Β",
    "Dgr": "Δ",
    "Egr": "Ε",
    "Igr": "Ι",
    "KHgr": "Χ",
    "Kgr": "Κ",
    "Lgr": "Λ",
    "Mgr": "Μ",
    "Ogr": "Ο",
    "Oragr": "Ὅ",
    "Orougr": "Ὁ",
    "PSgr": "Ψ",
    "Pgr": "Π",
    "Rgr": "Ρ",
    "Sgr": "Σ",
    "THgr": "Θ",
    "Tgr": "Τ",
    "Ugr": "Υ",
    "Xgr": "Ξ",
    "aacugr": "ά",
    "acirgr": "ᾶ",
    "acugr": "´",
    "agr": "α",
    "agragr": "ὰ",
    "arougr": "ἁ",
    "asmogr": "ἀ",
    "dgr": "δ",
    "eacugr": "έ",
    "eeacugr": "ή",
    "eegr": "η",
    "eegragr": "ὴ",
    "eeiotgr": "ῃ",
    "eeragr": "ἥ",
    "egr": "ε",
    "egragr": "ὲ",
    "esagr": "ἔ",
    "esmogr": "ἐ",
    "ggr": "γ",
    "iacugr": "ί",
    "igr": "ι",
    "igragr": "ὶ",
    "iragr": "ἵ",
    "irougr": "ἱ",
    "kgr": "κ",
    "khgr": "χ",
    "lgr": "λ",
    "mgr": "μ",
    "ngr": "ν",
    "oacugr": "ό",
    "ogr": "ο",
    "ogragr": "ὸ",
    "ohcigr": "ῷ",
    "ohcirgr": "ῶ",
    "ohgr": "ω",
    "ohigr": "ῳ",
    "ohrggr": "ὣ",
    "ohrgigr": "ᾣ",
    "oragr": "ὅ",
    "pgr": "π",
    "phgr": "φ",
    "psgr": "ψ",
    "rgr": "ρ",
    "rrougr": "ῥ",
    "rsmogr": "ῤ",
    "sfgr": "ς",
    "sgr": "σ",
    "tgr": "τ",
    "thgr": "θ",
    "uacugr": "ύ",
    "ucirgr": "ῦ",
    "ugr": "υ",
    "urougr": "ὑ",
    "usmogr": "ὐ",
    "xgr": "ξ",
}
